apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-registry-cleaner.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "docker-registry-cleaner.name" . }}
    helm.sh/chart: {{ include "docker-registry-cleaner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
{{- /* Ensure kubernetes namespace aligns with chart values */}}
{{- $cfg := deepCopy .Values.config -}}
{{- if not $cfg.kubernetes }}{{- $_ := set $cfg "kubernetes" dict }}{{- end }}
{{- $_ := set $cfg.kubernetes "domino_platform_namespace" .Values.dominoPlatformNamespace }}
{{ toYaml $cfg | indent 4 }}
