{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-registry-cleaner.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "docker-registry-cleaner.name" . }}-frontend
    helm.sh/chart: {{ include "docker-registry-cleaner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    # Select the StatefulSet pods (frontend is a sidecar)
    app.kubernetes.io/name: {{ include "docker-registry-cleaner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
